'lostpassword_reset_mail_sender' => 'noreply@workshoppy.net',
'lostpassword_reset_mail_subject' => 'Ihr Passwort wurde zurückgesetzt',
'lostpassword_reset_mail_body' => '
Hallo,

Ihr Passwort für workshoppy wurde zurückgesetzt

Sie können sich ab sofort mit folgendem Passort einloggen

__PASSWORD__',

'welcome_mail_title' => 'Willkommen!',
'welcome_mail_body' =>
'Hallo,

herzlich Willkommen auf workshoppy

Mit folgenden Daten können Sie sich auf der Homepage einloggen:

Username: __USERNAME__
Passwort: __PASSWORD__

',
