'default' => [
    'description' => 'workshop sessions',
    'fields'      => [
        'title' => [
            'title' => 'Title',
            'storage' => 'title',
            'type' => 'text',
            'widget' => 'text',
        ],
        'question' => [
            'title' => 'question',
            'storage' => 'question',
            'required' => true,
            'type' => 'text',
            'widget' => 'text',
        ],
    ],
],
